---
#- name: Perform Safe Upgrade
#  apt: upgrade=safe update_cache=yes

#- include: hostname.yml
#- include: swap.yml
#  when: swap_enabled is defined and swap_enabled == true
- include: tools.yml
- include: locale.yml

#- debug:
#    msg: "User is {{ deploy_user }} // {{ deploy_password }}"
