---
- group:
    name: deploy
    state: present

- name: Create Deploy user
  #remote_user: root
  #become: true
  #become_user: root
  user: 
    name={{ deploy_user }} 
    comment="Deploy User" 
    groups="sudo,deploy" 
    password="{{ deploy_password | password_hash('sha512') }}" 
    shell=/bin/bash 
    update_password=on_create
  

- name: Set authorized key took from files
  authorized_key:
    user: "{{ deploy_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_items:
    - '{{ ssh_authorized_keys }}'

- name: Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  #notify: Restart-sshd

  #- name: Disallow root SSH access
  #  lineinfile:
  #    dest: /etc/ssh/sshd_config
  #    regexp: "^PermitRootLogin"
  #    line: "PermitRootLogin no"
  #    state: present
  #    #notify: Restart-sshd
- name: restart-sshd
  remote_user: root
  service: name=ssh state=restarted
